### ISSUE TITLE
ERROR ReferenceError: MutationObserver is not defined

### ISSUE THREAD

**Issue by JAZzmiX** [staskolukasz/ngx-infinite-scroller#11]
Hi! Thanks for the ngx-infinite-scroller. 
On the client side, everything works fine but if run compile:server I have some error

> ERROR ReferenceError: MutationObserver is not defined
>     at NgxInfiniteScrollerDirective.registerMutationObserver (/Users/jazzmix/work/nuart.com.ua/App/dist/server.js:188972:40)
>     at NgxInfiniteScrollerDirective.ngOnInit (/Users/jazzmix/work/nuart.com.ua/App/dist/server.js:188949:14)
>     at checkAndUpdateDirectiveInline (/Users/jazzmix/work/nuart.com.ua/App/dist/server.js:22404:19)
>     at checkAndUpdateNodeInline (/Users/jazzmix/work/nuart.com.ua/App/dist/server.js:30660:20)
>     at checkAndUpdateNode (/Users/jazzmix/work/nuart.com.ua/App/dist/server.js:30622:16)
>     at prodCheckAndUpdateNode (/Users/jazzmix/work/nuart.com.ua/App/dist/server.js:31163:5)
>     at Object.updateDirectives (/Users/jazzmix/work/nuart.com.ua/App/dist/server.js:142174:2706)
>     at Object.updateDirectives (/Users/jazzmix/work/nuart.com.ua/App/dist/server.js:30951:72)
>     at checkAndUpdateView (/Users/jazzmix/work/nuart.com.ua/App/dist/server.js:30604:14)
>     at callViewAction (/Users/jazzmix/work/nuart.com.ua/App/dist/server.js:30845:21)
> TypeError: Cannot read property 'disconnect' of undefined
>     at NgxInfiniteScrollerDirective.ngOnDestroy (/Users/jazzmix/work/nuart.com.ua/App/dist/server.js:188957:34)
>     at callProviderLifecycles (/Users/jazzmix/work/nuart.com.ua/App/dist/server.js:22727:18)
>     at callElementProvidersLifecycles (/Users/jazzmix/work/nuart.com.ua/App/dist/server.js:22695:13)
>     at callLifecycleHooksChildrenFirst (/Users/jazzmix/work/nuart.com.ua/App/dist/server.js:22685:29)
>     at destroyView (/Users/jazzmix/work/nuart.com.ua/App/dist/server.js:30739:5)
>     at callViewAction (/Users/jazzmix/work/nuart.com.ua/App/dist/server.js:30865:13)
>     at execComponentViewsAction (/Users/jazzmix/work/nuart.com.ua/App/dist/server.js:30787:13)
>     at destroyView (/Users/jazzmix/work/nuart.com.ua/App/dist/server.js:30738:5)
>     at callViewAction (/Users/jazzmix/work/nuart.com.ua/App/dist/server.js:30865:13)
>     at execEmbeddedViewsAction (/Users/jazzmix/work/nuart.com.ua/App/dist/server.js:30808:17)

<img width="1277" alt="Снимок экрана 2019-07-04 в 00 51 17" src="https://user-images.githubusercontent.com/3510648/60627173-f38a8280-9df5-11e9-9ed4-9e1cb9276714.png">

**Comment by wbhob** [comment]
this is an issue with server rendering compatibility. I'll open up a PR in a little while because this is a problem we also need fixed.
