### ISSUE TITLE
@angular/http update to 8

### ISSUE THREAD

**Issue by ruisilva450** [staskolukasz/ngx-infinite-scroller#17]
Don't know why all @angular related dependencies are for 8 but ```@angular/http``` is still on 7. 

This should also be updated

**Comment by staskolukasz** [comment]
Hello!
Good catch! `@angular/http` was deprecated some time ago, please see:
https://www.npmjs.com/package/@angular/http
and it was also not used in this solution.

Reference to that package has been removed in that PR: https://github.com/staskolukasz/ngx-infinite-scroller/pull/18
